feat(Quantum/avatar): adds @quantum/Avatar component to simulator
catho/ssr-quantum-simulator pull request #16
Opened 2020-10-15 14:38 UTC by rapahaeru

- updates @catho-private/catho-components to version 1.13.0
- updates @catho/Quantum to version 6.4.9
- add  @catho/Quantum/Avatar to simulator
- add  @catho/Quantum/Badge (with dot) to simulator

2020-10-21 19:04 UTC, pedrosouza requested changes

2020-10-21 19:04 UTC, pedrosouza commented on package.json
> +    "@catho/quantum": "^6.4.1",
let's update to 6.4.2 already

2020-11-11 13:10 UTC, rapahaeru commented on package.json
> +    "@catho/quantum": "^6.4.1",
I did 6.4.9 already.

2020-11-24 13:01 UTC, rodrigoclemente approved these changes

2020-11-26 13:15 UTC, pedrosouza approved these changes

2020-11-26 13:16 UTC, merged