chore(CCOM-420): updates catho libs
catho/ssr-quantum-simulator pull request #48
Opened 2022-08-09 11:42 UTC by toncabral88

[ ] Code review
[ ] Build and start

2022-08-09 17:45 UTC, MarcosViniciusPC requested changes
![Captura de tela de 2022-08-09 14-35-42](https://user-images.githubusercontent.com/105747728/183722046-a1669594-859e-4a33-b110-d8b96578001b.png)

2022-08-10 20:18 UTC, MarcosViniciusPC approved these changes
[x ] Code review
[x] Build and start

2022-08-10 20:18 UTC, MarcosViniciusPC commented on package.json
> +    "node-sass": "^6.0.0",
What is this package used for?

2022-08-11 12:44 UTC, rapahaeru approved these changes
[x] Code review
[x] Build and start

2022-08-11 12:46 UTC, merged