Node sass removal
catho/ssr-quantum-simulator pull request #54
Opened 2023-03-03 13:37 UTC by alizeleal

2023-03-03 20:07 UTC, MarcosViniciusPC requested changes
[] Code review

Task Runners
[] Build
[] Dev

Delete widget import in pages/render.js file

When I gave a yarn to install the dependencies, the yarn.lock file was updated and I want to know if this situation happened to you?Can you test this? The test is simple, delete the node_modules folder and reinstall the dependencies using the `yarn` command. If the yarn.lock file is updated, commit this

![image](https://user-images.githubusercontent.com/105747728/222816326-922cbd95-7a53-44b5-988a-13cd1a376468.png)

2023-03-03 20:07 UTC, MarcosViniciusPC commented on package.json
> +
```suggestion
```

2023-03-03 20:10 UTC, rapahaeru requested changes

2023-03-03 20:10 UTC, rapahaeru commented on pages/cathocomponents.js
> -      <HeaderLoggedResponsive userProfile="STATUS_I_PROFISSIONAL" hasSearch />
This component  `HeaderLoggedResponsive` still exists in catho components, how about making it come back with it?

2023-03-07 12:03 UTC, MarcosViniciusPC approved these changes
[x] Code review

Task Runners
[x] Build
[x] Dev

2023-03-07 13:31 UTC, douglasjr97 approved these changes
## Review
- [x] Code review
- [x] Build
- [x] Dev

2023-03-07 13:41 UTC, merged