QTM-472 - Hide and Show Menu Function
catho/ssr-quantum-simulator pull request #61
Opened 2023-05-12 14:42 UTC by alizeleal

Description:

https://jirasoftware.catho.com.br/browse/QTM-472

Review guide:

[ ] Code Review
[ ] Layout

2023-05-15 14:23 UTC, rapahaeru requested changes

2023-05-15 14:23 UTC, rapahaeru commented on static_files/index.html
> +            <li><button class = "SandwichButton" id="ShowMenuButton">&#x2630;</button></li>
Is this id name make sense?
Id is a identification of element and its name shows me that it has a functionality. How about of "menuButton"?

2023-05-15 14:23 UTC, rapahaeru commented on static_files/index.html
> +      <nav id="HiddenMenu" class="HiddenMenu HideMenu">
how about of rename this id to "menu" only?

2023-05-15 14:23 UTC, rapahaeru commented on static_files/index.html
> +            <li><button class = "SandwichButton" id="ShowMenuButton">&#x2630;</button></li>
use `class="SandwichButton"` instead `class = "SandwichButton"`

2023-05-15 14:23 UTC, rapahaeru commented on static_files/css/style.css
>  .SandwichButton {
how about indicate to the user, that button is clickable?
Using `cursor: pointer`.

2023-05-15 14:23 UTC, rapahaeru commented on static_files/main.js
> +  if (Menu.classList.contains('HideMenu')) {
This is a advanced suggestion, do you want to implement right now?
I'll suggest to you, to use a object destructuring...

https://dmitripavlutin.com/javascript-object-destructuring/

what do you think?

2023-05-15 14:23 UTC, rapahaeru commented on static_files/main.js
> +const  Menu = document.getElementById("HiddenMenu");
Why did you prefer to get the element using `getElementById` instead `querySelector`, that you made in line `5`?

2023-05-15 14:23 UTC, rapahaeru commented on static_files/main.js
> +function MakeVisible (){
To make code clearer, how about of change the name of this function to a name that nake easier the reading? For example, `showMenu`?
Ps: functions names should use a camelCase (lowerCamelCase)

![image](https://github.com/catho/ssr-quantum-simulator/assets/3389749/04d3c3e0-cc9a-4288-a6aa-d86ac016b34c)

ih this case, makeVisible is a method.

https://coodesh.com/blog/dicionario/o-que-e-camelcase/#:~:text=Voc%C3%AA%20j%C3%A1%20ouviu%20falar%20em,com%20exce%C3%A7%C3%A3o%20do%20primeiro%20termo.

2023-05-16 19:40 UTC, alizeleal commented on static_files/index.html
> +      <nav id="HiddenMenu" class="HiddenMenu HideMenu">
Since there's the visible menu and a hidden menu, I believe it makes more sense to keep the name as hiddenMenu

2023-05-16 19:57 UTC, alizeleal commented on static_files/index.html
> +            <li><button class = "SandwichButton" id="ShowMenuButton">&#x2630;</button></li>
Fixed but wondering if there's a convention about these spaces

2023-05-18 13:09 UTC, rapahaeru approved these changes

2023-05-18 13:20 UTC, merged