CCOM-561 - Includes ESLint
catho/ssr-quantum-simulator pull request #69
Opened 2023-06-23 19:49 UTC by alizeleal

https://jirasoftware.catho.com.br/browse/CCOM-561

2023-06-28 17:23 UTC, MarcosViniciusPC requested changes
[] Code review

2023-06-28 17:23 UTC, MarcosViniciusPC commented on package.json
> +    "precommit": "lint-staged",
The prepush was missing, I did tests and the lint problems are not blocking the push

2023-06-29 11:56 UTC, MarcosViniciusPC approved these changes
[x] Code review
[x] Commit and push

2023-06-29 11:56 UTC, MarcosViniciusPC commented on .eslintrc.json
> +/* eslint-disable react/no-unescaped-entities */
```suggestion
```

2023-06-29 19:06 UTC, rapahaeru approved these changes

2023-06-29 19:06 UTC, rapahaeru commented on package.json
> +    "precommit": "lint-staged",
@alizeleal did you take this suggestion?

2023-06-30 14:32 UTC, merged