QTM-516 - Implements GRID on Header
catho/ssr-quantum-simulator pull request #75
Opened 2023-08-28 19:24 UTC by alizeleal

https://jirasoftware.catho.com.br/browse/QTM-516

Review:

- [ ] Docs
- [ ] Code Review

2023-08-29 18:23 UTC, MarcosViniciusPC requested changes
[] Code review

[x] Layout

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +    align-items: end;
Apparently these attributes are not required. You can verify?

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
>      gap: 50px;
Inside the div with the HiddenMenu class there is only one div. Do I need a gap and align here?

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +    justify-content: start;
```suggestion
```

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +    padding-right: 72px;
I believe that a padding of 12 px is enough, what do you think?

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +    color: #CCCCCC;
Was the color of the items different from the initial figma prototype?

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +        color: #CCCCCC;
.HiddenMenuNavigationItem already applies this color, do I really need to apply it again here?

2023-08-29 18:23 UTC, MarcosViniciusPC commented on static/style.css
> +    justify-content: flex-end;
This case is related to the use case of the class commenting above. justify-content: flex-end; it is only necessary when the class is used in nav. When used in Hide, this attribute is unnecessary. This demonstrates inconsistent use of the class for various purposes and can be difficult to maintain.

2023-08-29 18:23 UTC, MarcosViniciusPC commented on pages/_app.js
> +                    </Hide>
Using Hide here generates a new "div" with "li" inside. Semantically it doesn't make sense to have a list (ul) with a div that contains several "li" inside. Hiding the list items using media query from a class makes more sense than using the Hide component. Another point, the use of the VisibleMenu class is not clear. For example: Without looking at the css, what does the VisibleMenu class do?? Show the menu? Why does the button element not have the class and Hide does? He understands?

If the Hide component is removed, the
VisibleMenu class will be used in only one scenario, that is, its use becomes more predictable, you know?

2023-08-30 19:21 UTC, alizeleal commented on static/style.css
> +    padding-right: 72px;
Checked Figma again and indeed 12px is enough

2023-08-30 19:22 UTC, alizeleal commented on static/style.css
> +    color: #CCCCCC;
![image](https://github.com/catho/ssr-quantum-simulator/assets/48735281/bc7cfffc-3f64-43ec-bdae-2edeeaa3532a)
Yes! The other version was using the wrong color

2023-09-04 15:11 UTC, MarcosViniciusPC approved these changes
[x] Code review
[x] Layout

I suggest removing color from .MobileMenu ul

2023-09-04 18:59 UTC, merged