[QTM-582] Prepares SSR-Simulator for Unit Tests
catho/ssr-quantum-simulator pull request #93
Opened 2024-01-10 18:30 UTC by alizeleal

Description: https://jirasoftware.catho.com.br/browse/QTM-582

## Review guide
- [ ] Unit tests
- [ ] Code review

### Browsers review
- [ ] Layout review

2024-01-11 14:33 UTC, MarcosViniciusPC requested changes
[] Code review
[] Test

The tests didn't work here :(. Put "yarn" inside the "test:components" script to validate.

You need to configure Jest to test components that import .css and other files. In this case, it is necessary:

Create mock files in the project root called "jest-config.js", "styleMock" and "fileMock.js", similar to those in Quantum.

Create a prop called "jest" in ssr-simulator's package.json, also similar to Quantum.

Comments:

The "jest-config.js" file created in ssr-simulator should only have "import '@testing-library/jest-dom'".

Check the "Handling Static Assets" and "Mocking CSS Modules" sections of the doc https://jestjs.io/docs/webpack for more details on the above suggestions.


In addition to the points mentioned above, check the suggestions below.

2024-01-11 14:33 UTC, MarcosViniciusPC commented on components/ScrollUpButton/ScrollUpButton.unit.test.jsx
> +
```suggestion
```

2024-01-11 14:33 UTC, MarcosViniciusPC commented on package.json
> +    "test:components": "test ./components"
```suggestion
    "test:components": "yarn test ./components"
```

2024-01-11 14:33 UTC, MarcosViniciusPC commented on package.json
> +    "jest-css-modules": "^2.1.0",
```suggestion
```

2024-01-15 12:24 UTC, MarcosViniciusPC approved these changes
[x] code review
[x] test

2024-01-15 12:24 UTC, MarcosViniciusPC commented on package.json
> +    "test:components": "yarn test ./components"
Why not run "yarn jest..." directly instead of calling "yarn test..."?

2024-01-15 12:35 UTC, alizeleal commented on package.json
> +    "test:components": "yarn test ./components"
I'm following CC and Quantum's model ;)

2024-01-15 12:35 UTC, merged